<?php

/**
 * XynoServer — Génération des fichiers de configuration serveur
 *
 * GET /server-cms/api/generate_config.php?uuid=...&file=server.properties|eula.txt|start.sh|start.bat|whitelist.json
 *
 * Génère et télécharge le fichier de config du serveur Minecraft.
 */

declare(strict_types=1);

require_once __DIR__ . '/../config/bootstrap.php';

$user = current_user();
if ($user === null) {
    http_response_code(401);
    echo 'Non authentifié';
    exit;
}

$pdo  = db();
$uuid = trim((string)($_GET['uuid'] ?? ''));
$file = trim((string)($_GET['file'] ?? 'server.properties'));

if ($uuid === '') {
    http_response_code(400);
    echo 'UUID requis';
    exit;
}

$server = get_user_server($pdo, $user['id'], $uuid);
if (!$server) {
    http_response_code(404);
    echo 'Serveur introuvable';
    exit;
}

$config = json_decode((string)($server['server_config'] ?? '{}'), true) ?: [];

// Récupère les joueurs (whitelist)
$playersStmt = $pdo->prepare('SELECT mc_username, mc_uuid FROM mc_server_players WHERE server_id = ? AND whitelisted = 1');
$playersStmt->execute([$server['id']]);
$players = $playersStmt->fetchAll();

$allowedFiles = ['server.properties', 'eula.txt', 'start.sh', 'start.bat', 'whitelist.json', 'ops.json'];
if (!in_array($file, $allowedFiles, true)) {
    http_response_code(400);
    echo 'Fichier non supporté';
    exit;
}

$content = '';
$mimeType = 'text/plain; charset=utf-8';

switch ($file) {

    // ── server.properties ────────────────────────────────────────────────────
    case 'server.properties':
        $props = [
            '#Minecraft server properties',
            '#Generated by XynoServer CMS — ' . date('Y-m-d H:i:s'),
            '',
            'server-port=' . ((int)($server['server_port'] ?? 25565)),
            'motd=' . str_replace(["\n", "\r"], '', (string)($config['motd'] ?? $server['name'])),
            'max-players=' . ((int)($config['max-players'] ?? 20)),
            'online-mode=' . ($config['online-mode'] ?? true ? 'true' : 'false'),
            'difficulty=' . ($config['difficulty'] ?? 'normal'),
            'gamemode=' . ($config['gamemode'] ?? 'survival'),
            'pvp=' . ($config['pvp'] ?? true ? 'true' : 'false'),
            'enable-command-block=' . ($config['enable-command-block'] ?? false ? 'true' : 'false'),
            'spawn-protection=' . ((int)($config['spawn-protection'] ?? 16)),
            'view-distance=' . ((int)($config['view-distance'] ?? 10)),
            'simulation-distance=' . ((int)($config['simulation-distance'] ?? 10)),
            'white-list=' . ($config['white-list'] ?? false ? 'true' : 'false'),
            'enforce-whitelist=' . ($config['enforce-whitelist'] ?? false ? 'true' : 'false'),
            'level-name=world',
            'level-seed=',
            'allow-flight=false',
            'allow-nether=true',
            'generate-structures=true',
            'max-world-size=29999984',
            'enable-rcon=false',
            'sync-chunk-writes=true',
            'entity-broadcast-range-percentage=100',
            'player-idle-timeout=0',
            'prevent-proxy-connections=false',
            'use-native-transport=true',
            'enable-jmx-monitoring=false',
            'enable-status=true',
            'op-permission-level=4',
            'function-permission-level=2',
            'rate-limit=0',
            'broadcast-console-to-ops=true',
            'broadcast-rcon-to-ops=true',
        ];
        $content = implode("\n", $props) . "\n";
        break;

    // ── eula.txt ─────────────────────────────────────────────────────────────
    case 'eula.txt':
        $content  = "#By changing the setting below to TRUE you are indicating your agreement to our EULA\n";
        $content .= "#(https://aka.ms/MinecraftEULA)\n";
        $content .= '#Generated by XynoServer CMS — ' . date('Y-m-d H:i:s') . "\n";
        $content .= "eula=true\n";
        break;

    // ── start.sh (Linux/macOS) ────────────────────────────────────────────────
    case 'start.sh':
        $ram   = (int)($server['ram_mb'] ?? 2048);
        $jar   = get_server_jar_name($server);
        $flags = get_jvm_flags($ram);

        $content  = "#!/usr/bin/env bash\n";
        $content .= "# XynoServer CMS — Script de démarrage Linux/macOS\n";
        $content .= "# Serveur : " . $server['name'] . "\n";
        $content .= "# Type    : " . strtoupper((string)$server['server_type']) . " " . $server['mc_version'] . "\n\n";
        $content .= "cd \"\$(dirname \"\$0\")\"\n\n";
        $content .= "while true; do\n";
        $content .= "    java {$flags} -jar {$jar} nogui\n";
        $content .= "    echo \"\"\n";
        $content .= "    echo \"Serveur arrêté. Redémarrage dans 5 secondes... (Ctrl+C pour quitter)\"\n";
        $content .= "    sleep 5\n";
        $content .= "done\n";
        break;

    // ── start.bat (Windows) ───────────────────────────────────────────────────
    case 'start.bat':
        $ram   = (int)($server['ram_mb'] ?? 2048);
        $jar   = get_server_jar_name($server);
        $flags = get_jvm_flags($ram);

        $content  = "@echo off\r\n";
        $content .= "REM XynoServer CMS — Script de démarrage Windows\r\n";
        $content .= "REM Serveur : " . $server['name'] . "\r\n";
        $content .= "REM Type    : " . strtoupper((string)$server['server_type']) . " " . $server['mc_version'] . "\r\n\r\n";
        $content .= "cd /d \"%~dp0\"\r\n\r\n";
        $content .= ":start\r\n";
        $content .= "java {$flags} -jar {$jar} nogui\r\n";
        $content .= "echo.\r\n";
        $content .= "echo Serveur arrete. Redemarrage dans 5 secondes...\r\n";
        $content .= "timeout /t 5\r\n";
        $content .= "goto start\r\n";
        break;

    // ── whitelist.json ────────────────────────────────────────────────────────
    case 'whitelist.json':
        $mimeType = 'application/json; charset=utf-8';
        $list = [];
        foreach ($players as $p) {
            $list[] = [
                'uuid' => $p['mc_uuid'] ?? '00000000-0000-0000-0000-000000000000',
                'name' => $p['mc_username'],
            ];
        }
        $content = json_encode($list, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n";
        break;

    // ── ops.json (placeholder) ────────────────────────────────────────────────
    case 'ops.json':
        $mimeType = 'application/json; charset=utf-8';
        $content = json_encode([], JSON_PRETTY_PRINT) . "\n";
        break;
}

// ── Marquer le serveur comme "ready" après génération ─────────────────────
if ($file === 'server.properties') {
    $pdo->prepare('UPDATE mc_servers SET status = ?, generated_at = NOW() WHERE id = ?')
        ->execute(['ready', $server['id']]);
}

header('Content-Type: ' . $mimeType);
header('Content-Disposition: attachment; filename="' . $file . '"');
header('Content-Length: ' . strlen($content));
header('Cache-Control: no-cache');
echo $content;
exit;

// ─────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────

function get_server_jar_name(array $server): string
{
    $type    = (string)($server['server_type'] ?? 'paper');
    $mcVer   = (string)($server['mc_version'] ?? '');
    $loaderV = (string)($server['loader_version'] ?? '');

    return match ($type) {
        'vanilla' => "minecraft_server.{$mcVer}.jar",
        'paper'   => "paper-{$mcVer}-{$loaderV}.jar",
        'spigot'  => "spigot-{$mcVer}.jar",
        'forge'   => "forge-{$mcVer}-{$loaderV}.jar",
        'fabric'  => "fabric-server-mc.{$mcVer}-loader.{$loaderV}-launcher.0.12.1.jar",
        default   => 'server.jar',
    };
}

function get_jvm_flags(int $ramMb): string
{
    $xms = intdiv($ramMb, 2);
    // Flags Aikar optimisés pour MC
    return "-Xms{$xms}M -Xmx{$ramMb}M "
        . '-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 '
        . '-XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC '
        . '-XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 '
        . '-XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 '
        . '-XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 '
        . '-XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 '
        . '-XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 '
        . '-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true';
}
